{
	"name": "cpe:/a:python:python:3.10.0:-",
	"title": [
		{
			"text": "Python 3.10.0 -",
			"lang": "en-US"
		}
	],
	"references": [
		{
			"text": "Advisory",
			"href": "https://bugzilla.redhat.com/show_bug.cgi?id=1995234"
		},
		{
			"text": "Advisory",
			"href": "https://bugs.python.org/issue43075"
		}
	],
	"cpe_23_item": {
		"name": "cpe:2.3:a:python:python:3.10.0:-:*:*:*:*:*:*"
	}
}
